
export const ACCOUNT_CREATED = 'ACCOUNT/CREATED'
export const FORGOT_PASSWORD = 'FORGOT/PASSWORD'
export const INCREASE_COUNT = 'INCREASE/COUNT';

// Collection
export const COLLECTION_REQUEST = 'COLLECTION/REQUEST';
export const COLLECTION_RESPONSE = 'COLLECTION/RESPONSE';

// Collection
export const FLASHCARD_REQUEST = 'FLASHCARD/REQUEST';
export const FLASHCARD_RESPONSE = 'FLASHCARD/RESPONSE';

// Feedback
export const FEEDBACK_SUCCESS = 'FEEDBACK/SUCCESS';
export const FEEDBACK_FAILED = 'FEEDBACK/FAILED';

// Session
export const AUTHENTICATED = 'AUTHENTICATED/USER';
export const UNAUTHENTICATED = 'UNAUTHENTICATED/USER';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION/FAILED';

// User
export const STORE_USER = 'STORE/USER'
export const CLEAN_USER = 'CLEAR/USER'

export default {
  ACCOUNT_CREATED,
  FORGOT_PASSWORD,
  INCREASE_COUNT,
  FEEDBACK_SUCCESS,
  FEEDBACK_FAILED,
  AUTHENTICATED,
  UNAUTHENTICATED,
  AUTHENTICATION_FAILED,
  STORE_USER,
  CLEAN_USER,
  COLLECTION_REQUEST,
  COLLECTION_RESPONSE,
  FLASHCARD_REQUEST,
  FLASHCARD_RESPONSE,
}