
export function jwt() {
  return "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkdhYnJpZWwiLCJlbWFpbCI6ImdhYnJpZWwuc3Vha2lAaG90bWFpbC5jb20iLCJsb2dpbiI6ImdzdWFraSIsImNyZWF0ZWRfYXQiOiIyMDE4LTA4LTE3VDIxOjI5OjE5LjAwMFoiLCJpYXQiOjE1MzQ1NDEzNTl9.rBsbDMkqZmLIGtYPjMwjKrcPhwZDlCXhSkimmaADdW4";
}

export default {
  jwt
}